let topics [
  'What has been the most terrifying moment of your life so far ?',
    'If you could go back in time and change one thing in your life, what would it be and why?',
    'What is the best advice you have ever received?',
    'What is the worst advice you have ever received?',
    'What is your definition of success?',
    'What are your top three priorities in life?',
    'What is the biggest obstacle you have overcome?',
    'What has been the most rewarding experience of your life so far?',
    'Do you believe in fate or do you think we create our own destiny?',
    'What is the one thing that you are most proud of in your life?',
    'What is the one thing that you would like to change about yourself?',
    'If you could have any superpower, what would it be and why?',
    'What is your favorite book and why?',
    'What is your favorite movie and why?',
    'What is your favorite quote and why?',
    'What are your thoughts on social media?',
    'What is the most important lesson you have learned in life so far?',
    'What is the biggest risk you have ever taken?',
    'What is the best gift you have ever given or received?',
    'What has been your biggest failure, and what did you learn from it?',
    'What is the one thing you cannot live without?',
    'What has been your biggest accomplishment so far?',
    'What motivates you to get out of bed in the morning?',
    'What is your favorite hobby and why?',
    'What is the most interesting place you have ever visited?',
    'What are your thoughts on work-life balance?',
    'What do you think is the key to a happy and successful life?',
    'What is your favorite childhood memory?',
    'What is your favorite quote or saying?',
    'What is the one thing you would like to achieve in the next five years?',
    'What is the biggest challenge you are currently facing?',
    'What has been the most important decision you have ever made?',
    'What do you think is the meaning of life?',
    'What is your definition of true love?',
    'If you could switch lives with anyone for a day, who would it be and why?',
    'What is your greatest strength?',
    'What is your biggest weakness?',
    'What are your thoughts on the current state of the world?',
    'What is your favorite song and why?',
    'What is the best thing that has happened to you this year?',
    'What is the biggest lesson you have learned from a mistake?',
    'What has been the most difficult challenge you have faced in your career?',
    'What is your favorite way to relax and unwind?',
    'What has been your biggest regret in life?',
    'What are your thoughts on the concept of work?',
    'What is the most important quality for a successful career?',
    'What is your biggest pet peeve?',
    'What is your favorite way to spend time with family and friends?',
    'What is your favorite way to learn new things?',
    'What has been the most important decision you have ever made regarding your education?',
    'What is the biggest change you have ever made in your life?',
    'What is the biggest misconception people have about you?',
    'What is the most important thing you have learned from a mentor?',
    'What is your favorite way to give back to your community?',
    'What is your favorite place in the world and why?',
    'What is the one thing you wish you had more time for?',
  'What is something that you are failing in over again and again and why?',
'What is something that you do differently from most people?',
'What is something that you do that most people of your age do not and why?',
'What is something that you really enjoy and it is also helpful for your in long term ?',
'What is something that you wish to witness in your lifetime?',
'What is strength according to you?',
'What is the #1 thing=that you believe, is destroying our generation?',
'What is the difference between school life and college life ?',
'What is the first thing that you would buy/upgrade when your earnings will increase and why?',
'What is the most interesting thing about your college ?',
'What is the most senseless rule you have come across?',
'What is the one question / some questions that you ask yourself before doing anything?',
'What is the one thing you would like to completely eliminate from the world and why?',
'What is the thing that you find most weird in your surroundings?',
'What is wrong with today\'s youth?',
'What is your achievement that you have worked hardest for?',
'What is your greatest regret ?',
'What is your perception about people who join elite engineering colleges and do choose engineering as their career?',
'What is your recent achievement that makes you proud?',
'What kind of behaviour is a turn-off for you ?',
'What kind of films do you generally watch and why?',
'What kind of videos do you watch on YouTube? Why?',
'What makes something popular according to you?',
'What moment in your life would you like to go back in if you had a single-use time-travel machine which gets you back to the present after specified time?',
'What product do you think provides high value to you ?',
'What quality would you like to have less of ?',
'What should everyone realise by 20 years of age ?',
'What should one be proud of?',
'What should you be ashamed of?',
'What should you not be ashamed of?',
'What was the last time you have helped someone selflessly? How?',
'What was the most amazing transformation you saw in a person?',
'What was the most interesting thing about your school?',
'What will you buy with your first earnings and why ?',
'What you think,you become',
'What\'s difficult to understand for you?',
'What\'s the last time you have made someone feel nice, selflessly?',
'What\'s your biggest fear? Are you doing something to conquer it?',
'Whatever happens, happens for the good,',
'When was the last time a stranger has helped you selflessly ? How did you feel?,',
'When you think you have had a bad day, there is someone who had worse...',
'Which festival do you like the most and why?,',
'Who are you ?',
'Who is a mature person?',
'Who is a strong person according to you?',
'Why are most of the people unsuccessful in their lives?',
'Why are you chasing the thing you are chasing?',
'Why do you decide if something is important to you?',
'Why do you think is over-hyped right now?',
'Why is setting specific goals important?',
'Why should you exercise ?',
'Why should you not chase money?',
'Work hard in silence, let your success make the noise,',
'You are already ahead of the average person if you know what you want out of yourself over a time period',
     'A time when you had to make a difficult choice',
    'A time when you learned something valuable from a mistake',
    'A valuable lesson you learned from a challenge or obstacle you overcame',
    'A world without technology: How different would it be?',
    'Accept your present and work for your future',
    'Action speaks louder than words',
    'All that glitters is not gold',
    'Always be ready to say goodbye to anything',
    'Always say less than necessary',
    'Among the blind, one-eyed man is king',
    'Are most of the people killing themselves slowly?',
    'Are you a responsible citizen and how?',
    'Ask for it, the worst they will say is no',
    'At every point of life, we have a choice',
    'Be kind to others and ruthless with yourself',
    'Be process oriented not result oriented',
    'Be slow in choosing, but slower in changing',
    'Be thankful for the difficult times',
    'Be thankful that you don\'t already have everything you desire',
    'Be w̶i̶t̶h̶ someone that makes you happy',
    'Care about what other people think and you will always be their prisoner',
    'Change is the law of nature',
    'Character is how you treat those who can do nothing for you',
    'Choose your role-models wisely',
    'Describe a project (in layman\'s term) that you recently worked upon?',
    'Describe your childhood',
    'Describe your most terrifying experience',
    'Develop your mindset, the rest will be taken care of',
    'Do quick-fixes work?',
    'Do you believe in ghosts? Why?',
    'Do you believe someone easily? Why/Why not?',
    'Do you have a sibling (cousin)? Describe your relationship with him/her',
    'Does success lead to happiness?',
    'Don\'t miss the same opportunity twice',
    'Don\'t pray for an easy life, instead pray for the strength to endure a difficult one',
    'Don\'t share your ideas, share your results',
    'Don\'t trust words, trust actions',
    'Don\'t worry about things not in your control',
    'Every exit is an entry somewhere else',
    'Everyone has their own struggles',
    'Focus on the efforts not the goal',
    'Focus on yourself, not on others',
    'Friends: Have less but the best',
    'Give respect to expect respect',
    'Haste makes waste',
    'How are you different from others of the same age group?​',
    'How can you add an individual contribute to the betterment of the society?',
    'How do our habits shape us?',
    'How do you choose to do something?',
    'How do you deal with your insecurities?',
    'How do you deal with your life\'s problems?',
    'How do you decide to respect a person or not to?',
    'How do you initiate a conversation?',
    'How do you set your expectations?',
    'How insignificant are we?',
    'I can show you the way, but I cannot walk in your place',
    'If nothing else, some people teach you how not to be',
    'If something sounds too good to be true, then probably it is',
    'If you are given a chance to become the head of your institution/company, what are some of the changes that you would like to introduce?',
    'If you can control your time, you can achieve anything in life',
  'What is something that you do that most people of your age do not and why ?',
'What is something that you really enjoy and it is also helpful for you in the long term ?',
'What is something that you wish to witness in your lifetime?',
'What is strength according to you?',
'What is the #1 thing that you believe is destroying our generation?',
'What is the difference between school life and college life ?',
'What is the first thing that you would buy/upgrade when your earnings will increase and why?',
'What is the most interesting thing about your college ?',
'What is the most senseless rule you have come across?',
'What is the one question / some questions that you ask yourself before doing anything?',
'What is the one thing you would like to completely eliminate from the world and why?',
'What is the thing that you find most weird in your surroundings?',
'What is wrong with today\'s youth?',
'What is your achievement that you have worked hardest for?',
'What is your greatest regret ?',
'What is your perception about people who join elite engineering colleges and do choose engineering as their career?',
'What is your recent achievement that makes you proud?',
'What kind of behaviour is a turn-off for you ?',
'What kind of films do you generally watch and why?',
'What kind of videos do you watch on YouTube? Why?',
'What makes something popular according to you?',
'What moment in your life would you like to go back in if you had a single-use time-travel machine which gets you back to the present after specified time?',
'What product do you think provides high value to you ?',
'What quality would you like to have less of ?',
'What should everyone realize by 20 years of age ?',
'What should one be proud of?',
'What should you be ashamed of?',
'What should you not be ashamed of?',
'What was the last time you have helped someone selflessly? How?',
'What was the most amazing transformation you saw in a person?',
'What was the most interesting thing about your school?',
'What will you buy with your first earnings and why ?',
'What you think, you become',
'What\'s difficult to understand for you?',
'What\'s the last time you have made someone feel nice, selflessly?',
'What\'s your biggest fear? Are you doing something to conquer it?',
'Whatever happens, happens for the good,',
'When was the last time a stranger has helped you selflessly ? How did you feel?',
'When you think you have had a bad day, there is someone who had worse...',
'Which festival do you like the most and why?',
'Who are you ?',
'Who is a mature person?',
'Who is a strong person according to you?',
'Why are most of the people unsuccessful in their lives?',
'Why are you chasing the thing you are chasing?',
'Why do you decide if something is important to you?',
'Why do you think is over-hyped right now?',
'Why is setting specific goals important?',
'Why should you exercise ?',
'Why should you not chase money?',
'Work hard in silence, let your success make the noise',
'You are already ahead of the average person if you know what you want out of yourself over a time period',
'You are the sum of content you consume',
'You can\'t heal if you keep pretending you\'re not hurt',
'You can\'t learn from your mistakes if you do not accept them',
'You\'re not entitled to anything.'
   'What has been the most terrifying moment of your life so far ?',
    'What is your happiest memory ?',
    'What are you most excited about in your life right now-today ?',
    'The most successful person you know',
    'Wisdom vs Knowledge',
    'What is wealth?',
    'Smile, you are fine',
    'Focus only on what you can control',
    'Optimistic approach in life',
    'Your views on Addiction',
    'If every job had the same respect, power and money, what job would you do and why?',
    'Should you compare yourself with others?',
    'A subject that you have really liked during your college years?',
    'What is the biggest obstacle that stands in our way right now ?',
    'What music do you listen to lift your spirits when you are feeling down ?',
    'Do you want to be rich ? ',
    'Whenever you say yes to something, you are saying no to something else',
    'What is something you know you do differently than most people ?',
    'What do you have that you can not live without ?',
    'As a child , what did you want to be when you grew up ?',
    'Are you happy with yourself ?',
    'Does hardwork always lead to success?',
    'Is it ok to cheat?',
    'Is there such a thing as useless ?',
    'Is it ok to steal?',
    'Have you stolen something in your life?',
    'What is your perfect vacation?',
    'Do you judge people from their first impression?',
    'How much money will be enough for you to live your dream life.Explain',
    'Has there been a moment in your life where you instantly lost respect for a person?',
    'What is financial freedom, according to you?',
    'What are the things that you think are not worth the risk no matter how much is the potential gain ?',
    'What do you sometimes pretend to understand that you really do not ? ',
    'How would you spend your ideal day ? ',
    'Share something unusual about yourself',
    'What word best describes the way you have spent the last month of your life ?',
    'What have you worked hard on and loved every minute of it ?',
    ' What have you worked hard on even when you did not like it ?',
    'What is the nicest thing someone has ever done for you ?',
    'What bad habits do you want to break ?',
    'What do you think that you are better at than most of the people ?',
    'Should you do what you love or love what you do ?',
    'What is the strongest person you know ?',
    'What was the last time you felt lucky ?',
    'What is the most defining moment of your life so far ?',
    'When you have a random hour of free time, what do you usually do ?',
    'Personal finanace advice',
    'What is the least that parents should expect from their child(ren)?',
    'Do you like to live by abiding rules?',
    'What makes life easier ?',
    'What is one of your recent purchases which, you believe, is helping you a lot in your life?',
    'Is earning money easy?',
    'What is wrong with our generation?',
    'One thing that you bought and then regretted later for buying it',
    'What is the one thing that you think most of the people do in the wrong way?',
    'Which social media platform do you use the most and why?',
    'How to earn money?',
    'Do you like flex culture ?',
    'What is the most common thing among our previous generation (our parents) which is not so common among us?',
    'What are some of the things that we, as human beings, are getting better at ?',
    'What are some of the things that we , as human beings, are getting worse at ?',
    'What questions do you often ask yourself ?',
    'What one thing do you want to change in this world ?',
    'What is the most recent dream you remember having while sleeping ?',
    'Why do you matter ?',
    'What have you read online recently that inspired you ?',
    'What are you sure of in your life ?',
    'What is the number one quality that makes a person successful ?',
    'What was your last major accomplishment ?',
    'What is your most prized possesion ?',
    'What is worse failing or never trying ?',
    'What are you acertain about ?',
    'What life lesson did you learn the hard way ?',
    'What do you love to practice ?',
    'What seems too good to be true?',
    'As a kid , which subject did you hate the most?',
    'What do you imagine yourself doing ten years from now ?',
    'How do you spend majority of your free time ?',
    'What do you miss the most from your childhood ?',
    'What are your top three priorities ?',
    'What is the right age to start earning?',
    'What ,according to you, is projected as a reality but is actually fake?',
    'Who do you think was the most interesting person in history?',
    'Reality is often dissapointing',
    'What do you think is changing rapidly as we are progressing into the future?',
    'What is your favorite incident from your life that you enjoy sharing with others ?',
    'What is a belief that you hold that many people disagree with ?',
    'Who or what is the greatest enemy of mankind ?',
    'Who is your role model ?',
    'Are you a people-pleaser?',
    'A recent video or an article which you watched or read which you think is worth sharing?',
    'What can you do now that you were not capable of a year ago ?',
    'What job would you never do no matter how much it paid ?',
    'What do you want most ?',
    'If you wanted to live one day of your life over again, what day would you choose ?',
    'What are the three moral rules you will never break ?',
    'Which cewlebrity do you admire and why?',
    'What is your high school memory that you cherish even today ?',
    'What is the one thing that you would like to advise your younger self?',
    'If you had 1 hour extra per day, what would you do ?',
    'If you had a chance to go back to past and change one thing, what would that be ?',
    'Who depends on you ?',
    'What is the one thing that very few people know about you?',
    'What do you see when you look into the future ?',
    'Is there such a thing as perfect ?',
    'What is the one thing that will change the most in the next ten years ?',
    'What is your biggest fear ?',
    'What has fear of failure stopped you from doing ?',
    'What confuses you ?',
    'If you could message all the people around the world for once, what message would it be ?',
    'What makes you proud ?',
    'What is the biggest change that you have made in your life in the last year ?',
    'If you could ask a person, alive or dead, only one question , who would you ask and what ?',
    'Have you regretted something you did not say or do ? ',
    'What do you love most about yourself ?',
    'What is the one thing that you have not done that you really want to do ?',
    'If you move abroad, wat is the one thing that you will miss about India ?',
    'Are professional athletes and actors paid too much ?',
    'What do you know well enough to teach to others ?',
    'If you had a chance to become a teacher, what would you teach ?',
    'What is the least that you expect from others ?',
    'What is your most favorite hobby ?',
    'Do looks matter ?',
    'What was the last thing that made you laugh loud ?',
    'What can you over and over without getting bored ?',
    'Is there ever a time when giving up makes sense ?',
    'A person you would like to meet once in your lifetime',
    'Three things you believe that everyone should do ',
    'What is the best time for a kid to get a personal phone',
    'Beliefs you had 5 years ago which have been proven wrong ?',
    'Do you think academics and formal education are overhyped ?',
    'Describe a show that you would watch on TV a kid',
    'What do you think of money ?',
    'How to make your favorite meal ?',
    'What is success ? ',
    'Describe a turning point of your life ? ',
    'What is the best advice your parents ever gave you ? ',
    'If you had a single use time machine , would you go to past or future ? ',
    'Describe your hometown or birthplace. ',
    'If you had to be famous , what would you want it to be for ? ',
    'What is the best book you have ever read ? ',
    'If you get 1 cr rupees now , how would you spend it ? ',
    'Are you a early riser or late sleeper? Would you rather be opposite? ',
    'What has the COVID-19 pandemic taught us?',
    'What goals have you set for you this year ?',
    'What do you miss the most from your college life?',
    'What is happiness? ',
    'What can someone do to grab your attention?',
    'What do you wish you spent more time doing five years ago?',
    'What worries you about the future?',
    'Who is a hero according to you ? ',
    'Where or who do ytou turn to when you need good advice?',
    'Should parents decide what should their child become in future?',
    'What was a quick decision you once made that changed your life?',
    'How are you pursuing your dreams right now ?',
    'What thing have youu done lately that is worth remembering ? ',
    'Are you more like yor mom or dad and in what way ? ',
    'What do you wish you should have done differently? ',
    'Any movie or web-series that you recently watched which was worth the time ?',
    'What motivates to keep working hard ? ',
    'What human quality do we need more of?',
    'In one year from today, how do you think your life will be different?',
    'What is the most important lesson that you learnt last year?',
    'How are you different from most of the people ? ',
    'What is the most enjoyable thing that you have done with your family members recently?',
    'Which activities make you lose track of time?',
    'What opportunities have you missed deliberately that you wished you have opted for ?',
    'Are you happy with where you are in your life?',
    'What is the last time you have helped someone selflessly?',
    'Tell a story.',
    'A moment in your life when you felt like giving up but did not do so',
    'Is success limited?',
    'A recent positive change that you brought in your life',
    'Expectations vs reality after entering college',
    'Describe your ideal day',
    'Describe your favorite vacation',
    '3 things that you learned in the past twelve months',
    '3 things you wish to learn in the next three months',
    'Describe a film or a web series which you have watched recently',
    'What is fitness?',
    'What is the one human quality that you hate the most?',
    'What is the one human quality that you like the most?',
    'What differentiates a successful and an unsuccessful person?',
    'What is financial independence?',
    'What are your strengths and weaknesses?',
    'What makes your angry?',
    'What makes you happy?',
    'What is something you would like to see in your lifetime and why?',
    'Has there ever been a time where you needed to make a decision without knowing all of the details of a situation?',
    'Have you ever foreseen a problem before it happened? What did you do to prevent this from happening?',
    'Describe a color of your choice to someone who is blind .' ,
    'What steps do you take when addressing a problem?',
    'If I were a super hero my superpower would be…',
    'A job I’d love to have',
    '2 or 3 things I will never eat… because…',
    'If I could only eat three foods forever',
    'The best movie ever (2 or 3 reasons why)',
    'An important lesson I’ve learned from my life',
    'If you were the leader of your country, what changes would you make to the current state of your nation and why?',
    'In your opinion, what is the most fundamentally urgent issue in our world, and why do you feel this way?',
    'What single thing in your opinion causes the most harm to us as a society, and how is it avoidable?',
    'Can human nature ever be changed? If so, how should it be changed and why?',
    'If you could create only three laws for people to live by, what would they be and why?',
    'Do you believe the world could exist without the concept of material wealth? How would it be different than it is now?',
    'If you could choose a superpower for you , which one should it be ?',
    'Do we have a moral obligation to help those less fortunate than we are? Why or why not?',
    'What harsh truths about life do you prefer to consciously ignore, and why?',
    'If you had to either lie or speak truth everytime , which one would you prefer ?',
    'Is humanity inherently ‘good’ or inherently ‘evil?’ Why do you feel this way?',
    'Do you consider the effects of our words and actions on other people?',
    'How do you explain your favourite subject to a kid ?',
    ' What is development according to you?',
    'Explain 3 lessons you’ve learned so far while attending college',
    'The personal achievement I’m most proud of is… (because…)',
    'The greatest gifts we can give others are…',
    'According to you ,what is underrated?',
    'According to you ,who is underrated?',
    'Your vision or your hearing ; which one of the two would you choose if you had to choose any one of them?',
    'What is a good job according to you?',
    'If you are offered a holiday package to your preferred location, where would you like to go?',
    'Is peer pressure beneficial for the development of a student ?',
    'If you had a chance to build a startup , what category would it belong to?',
    'If you become the education minister of your country , what changes would you suggest in the school system?',
    'Does our technology connect us more, or isolate us more? Why do you feel this way?',
    'How is our perception of good and evil shaped by our films, books, and video games?',
    'Are you in the rat race and why ?',
    'Are you worried about what people think about you?',
    'A thing that you use in your daily life ',
    'Explain 3 things you wish you knew before entering college',
    'When I was a kid I was afraid of',
    'My favorite season is… because…',
    'My favorite summer holidays memory from childhood',
    'What is your favorite animal and why?',
    'According to you,what is overrated?',
    'According to you,who is overrated?',
    'What seems easy to do but is actually hard?',
    'Would you prefer to be deaf or blind right from your birth?',
    'Which sport would you like to learn?',
    'What kind of songs do you generally listen to and why?',
    'Which is the one thing that you have spent ridiculous amount of money on?',
    'What are you known for among your friends or family?',
    'What kind of weather do you like?',
    'A thing in your life which you did in the past which makes no sense to you now',
    'If you can go back in time and talk to yourself, what you would advise your younger self ?',
    'What did you want to become as a child?',
    'What is your phobia?',
    'Who is a gentleman according to you?',
    'What is difficult for you?',
    'What is a thing that most of the people do not know about you but you would want yourself to be known as?',
    'A recent incident where you were got angry but could not/ did not do anything',
    'If you could be of any age for one week, what age and why?',
    'Imagine that you are a mirror. Describe your life.',
    'Imagine that you are a shoe. Describe your life.',
    'Imagine that you are a tree. Describe your life.',
    'Sell a flying car to the people present here.',
    'Sell a speaking parrot to the people present here.',
    'Talk about your favorite color',
    'Where would you choose to live if you had to leave this country?',
    'What is your favorite family tradition',
    'What excites you about the future?',
    'What movie made you laugh really hard?',
    'Is it good to give money to the children who beg?What would you do?',
    'What are you thankful for?',
    'Who is funniest person you know?',
    'What is the most difficult thing about getting older?',
    'Which is the most beautiful place you have seen?',
    'Who or what is sure to make you laugh?',
    'What is something new that you would like to try this year?',
    'What do you think of first when you wake up in the morning?',
    'What would be the hardest thing about climbing Mt. Everest?',
    'What gift would you like to receive on your birthday?',
    'Sell a feature phone/keypad phone to the people present here.',
    'Why do you think people behave the way they do ?',
    'Describe your college.',
    'What is the significance of life?',
    'What do you think about the government of your country?',
    'An unusual thing that you saw or read recently',
    'Interpret the quote:Time is money',
    'Who would you like to be your neighbour?',
    'What are the three most important inventions/discoveries which have changed the course of human life?',
    'What would you like to gift your parents?',
    'Do you believe in God?Why?',
    'Do you pray ? Why?',
    'What is something that you feel is wrong with our generation?',
    'What is something that you feel we are colectively doing wrong?',
    'Is lying ok?',
    'Do you have complete control of your life?',
    'Is giving pocket money to children a good practice?',
    'What habit would you like to break?',
    'Would you rather be self-employed or salaried?',
    'What is the most ironical thing you have come accross?',
    'What is something that you tried once and never want to try again?',
    'Whom do you hate the most?',
    'Would you rather be in high pain which last for a short time or low pain which last for long time?',
    'Three things everyone should do well',
    'An important lesson that I learned after doing a mistake',
    'Things you can not learn at school or college',
    'How to learn a thing that you recently learned?',
    'Three things that you are scared of',
    'Your favorite fictional character',
    'What is reality?',
    'Narrate a funny incident from your life',
    'How do you define an average person?',
    'How do you usually start a conversation?',
    'What is the biggest lie that most people tell themselves?',
    'What is the most creative ad you came accross?',
    'If you were not in the field you are in currently, where do you imagine yourself ?',
    'What is easy but people complicate it?',
    'What are some of the movies that you think are a must-watch?',
    'What is your renet purchase which you think provided you more value for the money?',
    'What is the most important invention/discovery , according to you?',
    'What are you outside of your current job/education?',
    'What things did you believe 5 years ago which have been proven wrong for you?',
    'What is the last thing that you have done selflessly for a stranger?',
    'Describe your country',
    'Describe your state',
    'Discuss one of your good habits',
    'Do you think you are led by circumstances or did you carve your own path?',
    'Whay is the last time you helped someone and how?',
    'What is something you know you are doing wrong?',
    'What is a thing that you can do without much effort while most of the people struggle to do it?',
    'Discuss one of the habits that makes you different from most of the people',
    'Discuss an amusing experience you had recently ',
    'What are you fed up of ? ', 
    'What thing did you believe to be true in your childhood which in fact was a lie ',
    'What do you wish to learn and why?',
    'What have you realised late in your life?',
    'What did you realise early in your life which helped you significantly ?',
    'Good things take time',
    'What seems easy to do but is actually hard?',
    'What is something uncommon that you enjoy doing while most the people do not?',
    'What makes life hard ?',
    'What makes life easy?',
    '3 advices that you would like to give your younger self.',
    'What is your understanding about mental depression?',
    'Why are friends important?',
    'What is something that you did today that you could do in a better way?',
    'A stitch in time saves nine',
    'What is something that most of the people around you do you believe is wrong?',
    'Do you consider yourself a lucky or an unlucky person? Why ?',
    'What is stopping you from achieving something that you want to achieve?',
    'Describe a place you have recently been to ',
    'Simple vs Easy',
    'How do you cool yourself down when you are angry ?',
    'An encounter with a stranger which made you feel happy/relaxed ',
    'Who is/was your favorite teacher and why?',
    'What is something that you learnt recently ?',
    'One productivity hack that you use?',
    'If you get a chance to operate on of the ministries of your country, what would you choose and why?',
    'To improve our world, what are the 3 actions, you believe, we should take?',
    'Should you talk to strangers?',
    'An encounter with a stranger that turned out quite a good experience?',
    'You can spoon-feed people, but you cannot chew and digest for them',
    'What is fear ?',
    'Do you follow a schedule or do things as they come?',
    'What is the most useless invention you have come across?',
    'Share a supernatural experience that you have had in the past',
    'What do you look for in a person before choosing them as your friend ?',
    'What is the most delicious thing that you have eaten? Describe it .',
    'Do you try to conquer your fears? How ?',
    'What are you planning to do and what is stopping you from doing it?',
    'What is easy but people perceive it to be difficult ?',
    'Do you follow the news? What kind of news do you follow ?',
    'What is something that you do regularly which has made you a better person overall?',
    'When is the last time you have helped someone? How?',
    'Do you like pets? Why/Why not?',
    'Do you believe in karma ( As you sow, so shall you reap) ?',
    'What movie can you watch over again and again?',
    'Do you exercise? Why/ Why not ?',
    'Do you have any skill/talent that most of the people do not have?',
    'Do not judge a book by its cover',
    'Whether you think you can or you cannot , you are right- Henry Ford',
    'Do you play any sport? Why?',
    'Justify the purpose of any movie/web-series villain',
    'Who has been the most influential person in your life and why?',
    'What have you recently explored/ learned about and found it fascinating/interesting?',
    'What are some of the things that a student should do during their college life?',
    'If you were not a human, what living organism would you want to be?',
    'What comes to your mind when you hear the word discipline?',
    'The most difficult thing you have ever done',
    'Have you ever been a victim of fraud? Share your experience?',
    'What is the biggest fraud that you have came accross?',
    'What things must parents teach their kids?',
    'Why do most of the people fear public speaking?',
    'The most useful things in life are free. Discuss'
    
]
